---
- name: allow binding to IPs not currently on this system
  sysctl: name=net.ipv4.ip_nonlocal_bind value=1

- name: install haproxy
  yum: name={{ item }}
  with_items:
   - haproxy
   - bind-utils

- name: copy haproxy configuration file
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg owner=root group=root mode=0644

- name: start haproxy service
  service: name=haproxy state=started enabled=yes
  when: pacemaker_service_control == false

- name: determine ipaddress for haproxy floating ip
  shell: dig +short {{ openstack_controller_public_address }} | tail -n1
  register: ipaddr_output
  changed_when: false
  always_run: true
  run_once: true

- name: create the floating ip within pacemaker
  pcs_resource:
    command: create
    name: public_vip
    type: ocf:heartbeat:IPaddr2
    options:
      ip: "{{ ipaddr_output.stdout }}"
  run_once: true

- name: create the haproxy resource within pacemaker
  pcs_resource:
    command: create
    name: haproxy
    type: systemd:haproxy
    clone: yes
    operations:
      - action: monitor
        options:
          start-delay: 10s
  run_once: true
  when: pacemaker_service_control == true
