heat_template_version: 2013-05-23

description: Deploy an layout ready for Openstack Deployment

parameters:
  compute_count:
    description: Number of Compute Nodes in this Openstack Environment
    type: number
    default: 3
    constraints:
    - range:
        min: 3
        max: 12
      description: Must be between 3 and 12 servers.
  key-name:
    type: string
    description: Name of key-pair to be used for instances
  flavor:
    type: string
    default: m1.medium
    constraints:
    - allowed_values:
      - m1.small
      - m1.medium
      - m1.large
      description: |
        Must be a valid Openstack Cloud Server flavor for the region you have
        selected to deploy into. This is the size of the compute nodes
  image_id:
    type: string
    description: UUID of image to use for the instaces

resources:
  open_security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      description: open rule for openstack
      name: openstack
      rules: [{"remote_ip_prefix": "0.0.0.0/0", "port_range_min": 1, "port_range_max": 65535, "protocol": "tcp"}, {"remote_ip_prefix": "0.0.0.0/0", "port_range_min": 1, "port_range_max": 65535, "protocol": "udp"}]

  management_network:
    type: "OS::Neutron::Net"
    properties:
      name: "management"

  management_subnet:
    type: "OS::Neutron::Subnet"
    properties:
      network_id: { get_resource: management_network }
      cidr: "192.168.10.0/24"

  tenant_network:
    type: "OS::Neutron::Net"
    properties:
      name: "tenant"

  tenant_subnet:
    type: "OS::Neutron::Subnet"
    properties:
      network_id: { get_resource: tenant_network }
      cidr: "192.168.11.0/24"

  floating_ip_network:
    type: "OS::Neutron::Net"
    properties:
      name: "floating ip"

  floating_ip_subnet:
    type: "OS::Neutron::Subnet"
    properties:
      network_id: { get_resource: floating_ip_network }
      cidr: "192.168.12.0/24"

  public_router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info:
        network: "public"

  coreos_router_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: public_router }
      subnet_id: { get_resource: management_subnet }

  operations_management_router_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: public_router }
      subnet_id: { get_resource: floating_ip_subnet }

  controller_machines:
    type: "OS::Heat::ResourceGroup"
    depends_on: management_subnet
    properties:
      count: 3
      resource_def:
        type: OS::Nova::Server
        properties:
          key_name: { get_param: key-name }
          image: { get_param: image_id }
          flavor: m1.medium
          name: openstack-controller
          networks:
            - { network: { get_resource: management_network } }
          security_groups:
            - { "Ref" : "open_security_group" }

  compute_machines:
    type: "OS::Heat::ResourceGroup"
    depends_on:
      - management_subnet
      - tenant_subnet
    properties:
      count: { get_param: compute_count }
      resource_def:
        type: OS::Nova::Server
        properties:
          key_name: { get_param: key-name }
          image: { get_param: image_id }
          flavor: { get_param: flavor }
          name: openstack-compute
          networks:
            - { network: { get_resource: management_network } }
            - { network: { get_resource: tenant_network } }
          security_groups:
            - { "Ref" : "open_security_group" }

  network_machines:
    type: "OS::Heat::ResourceGroup"
    depends_on: 
      - management_subnet
      - floating_ip_subnet
    properties:
      count: 3
      resource_def:
        type: OS::Nova::Server
        properties:
          key_name: { get_param: key-name }
          image: { get_param: image_id }
          flavor: m1.medium
          name: openstack-network
          networks:
            - { network: { get_resource: management_network } }
            - { network: { get_resource: floating_ip_network } }
          security_groups:
            - { "Ref" : "open_security_group" }
