---
### Baremetal setup
#pacemaker_cluster_stonith_settings: fence_ipmilan auth=md5 ipaddr=openstack-controller-01-drac.test.local login=root passwd=secret action=reboot pcmk_host_check=static-list pcmk_host_list=openstack-controller-01.test.local

### Virtual Machine setup openstack-controller-pefcyn4jyvlt-0-a5brqyscv7zd
#pacemaker_cluster_stonith_settings: fence_virt port=openstack-controller-pefcyn4jyvlt-0-a5brqyscv7zd action=reboot pcmk_host_check=static-list pcmk_host_list=openstack-controller-pefcyn4jyvlt-0-a5brqyscv7zd.novalocal
pacemaker_cluster_stonith_settings: fence_virt port=422349c6-dc21-40b2-8dca-43676e345ff0 action=reboot pcmk_host_check=static-list pcmk_host_list=openstack-controller-pefcyn4jyvlt-0-a5brqyscv7zd.novalocal

