---
neutron_server_tunnel_interface: p2p2
openstack_network_external_interface: p3p1
pacemaker_cluster_stonith_settings: fence_ipmilan auth=md5 ipaddr=openstack-network-02-drac.test.local login=root passwd=secret action=reboot pcmk_host_check=static-list pcmk_host_list=openstack-network-02.test.local
