---
- name: install horizon packages
  yum: name={{ item }}
  with_items:
    - openstack-dashboard

- name: copy horizon configuration file
  template: src=local_settings.j2 dest=/etc/openstack-dashboard/local_settings owner=root group=apache mode=0640

- name: edit apache configuration file to only listen on one interface
  lineinfile: dest=/etc/httpd/conf/httpd.conf regexp='^Listen .*80$' line='Listen {{ ansible_default_ipv4.address }}:80'

- name: open firewall for horizon
  firewalld: port={{ item[1] }} state=enabled permanent={{ item [0] }}
  with_nested:
    - [ true, false ]
    - [ '80/tcp', '443/tcp' ]

- name: start and enable horizon service
  service: name=httpd state=started enabled=yes
