- name: install glusterfs packages
  yum: name=glusterfs-fuse

- name: install libvirt package
  yum: name=libvirt

- name: ensure libvirtd is running
  service: name=libvirtd state=started enabled=yes

#- name: open firewall for nova
#  firewalld: port={{ item[1] }} state=enabled permanent={{ item [0] }}
#  with_nested:
#    - [ true, false ]
#    - [ '5900-5999/tcp' ]

- name: Start the services for nova
  service: name={{ item }} state=started enabled=yes
  with_items:
   - openstack-nova-compute
