---
# The common tasks

- name: disable selinux
  selinux: state=permissive policy=targeted

## This is only used for a test deployment or if you have no DNS configured
- name: Copy hosts file to test nodes
  copy:
    src: hosts
    dest: /etc/hosts owner=root group=root mode=0644

#- name: enable needed channels
#  redhat_subscription: username={{ redhat_username }} password={{ redhat_password }} pool='{{ item }}'
#  with_items:
#    - 'Red Hat Enterprise Linux Server'
#    - 'Red Hat Enterprise Linux OpenStack Platform for Controller Nodes, Premium (2-sockets)'
#  register: redhat_subscription

#- name: refresh repos from subscription manager
#  shell: subscription-manager repos
#  when: redhat_subscription.changed

#- name: disable all yum repos
#  shell: yum-config-manager --disable '*'
#  when: redhat_subscription.changed

#- name: enable repos we need only
#  shell: subscription-manager repos --enable={{ item }}
#  with_items:
#    - rhel-7-server-openstack-5.0-rpms
#  when: redhat_subscription.changed

#- name: Disable iptables
#  service: name=iptables state=stopped enabled=no

#- name: Create the rhel 7 server, optional repository
#  template:
#    src: rhel-7-server-optional-rpms.repo.j2
#    dest: /etc/yum.repos.d/rhel-7-server-optional-rpms.repo

- name: Create the rhel 7 server repository
  template:
    src: rhel-7-server-rpms.repo.j2
    dest: /etc/yum.repos.d/rhel-7-server-rpms.repo

- name: Create the rhel 7 ha repository
  template:
    src: rhel-ha-for-rhel-7-server-rpms.repo.j2
    dest: /etc/yum.repos.d/rhel-ha-for-rhel-7-server-rpms.repo

- name: Create the rhel 7 openstack repository
  copy:
    src: rhel-7-server-openstack-5.0-rpms.repo
    dest: /etc/yum.repos.d/rhel-7-server-openstack-5.0-rpms.repo
