---
- hosts: openstack-controller:openstack-compute:openstack-network
  roles:
    - common

- hosts: openstack-controller
  roles:
    - openstack/controller

- hosts: openstack-compute
  roles:
    - openstack/compute

- hosts: openstack-network
  roles:
    - openstack/network
