---
## This with create a demo Virtual machine Openstack Cloud config based on 6 VM's
- hosts: openstack-controller:openstack-compute:openstack-network       
  gather_facts: yes
  tasks: 
   - command: hostname   
  
