---
- name: disable NetworkManager
  service: name=NetworkManager state=stopped enabled=no

- name: disable firewalld
  service: name=firewalld state=stopped enabled=no

- name: symlink ml2 agent configuration as /etc/neutron/plugin.ini
  file: src=/etc/neutron/plugins/openvswitch/ovs_neutron_plugin.ini dest=/etc/neutron/plugin.ini owner=neutron group=neutron state=link

#- name: open firewall for vxlan
#  firewalld: port={{ item[1] }} state=enabled permanent={{ item [0] }}
#  with_nested:
#    - [ true, false ]
#    - [ '4789/udp' ]

- name: enable and start the openvswitch service
  service: name=openvswitch state=started enabled=yes

- name: Create the internal bridge for openvswitch
  openvswitch_bridge: bridge=br-int state=present

- name: Create the tunnel bridge for openvswitch
  openvswitch_bridge: bridge=br-tun state=present

- name: Ensure cleanup services run at boot
  service: name={{ item }} enabled=yes
  with_items:
    - neutron-ovs-cleanup
    - neutron-netns-cleanup

- name: Start the neutron services
  service: name={{ item }} state=started enabled=yes
  with_items:
    - neutron-openvswitch-agent
